languageCode = "en-us"
title = "Museum of Brick"
baseURL = "https://museumof.ca/"
theme = "brick"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[permalinks]
  post = "/:slug/"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
